# Generated by Django 6.0.4 on 2026-06-27 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="enablebanking", max_length=32)),
                ("aspsp_name", models.CharField(max_length=120)),
                ("country", models.CharField(default="IT", max_length=2)),
                ("state", models.CharField(max_length=64, unique=True)),
                ("encrypted_session", models.BinaryField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("consent_valid_until", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_detail",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_uid", models.CharField(max_length=128)),
                (
                    "iban_masked",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("last_synced_booking_date", models.DateField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="banksync.bankconnection",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("connection", "external_uid"),
                        name="uniq_account_per_connection",
                    )
                ],
            },
        ),
    ]
