# Generated by Django 6.0.4 on 2026-06-27 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_categorizationrule_financesettings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="dedup_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("enablebanking", "Enable Banking"),
                    ("import", "File import"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("user", "source", "external_id"),
                name="uniq_tx_source_external",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_hash", ""), _negated=True),
                fields=("user", "dedup_hash"),
                name="uniq_tx_dedup_hash",
            ),
        ),
    ]
