# Generated by Django 6.0.4 on 2026-06-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banksync", "0001_initial"),
        ("finance", "0003_transaction_dedup_hash_transaction_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="banksync.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_transfer",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer_pair",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="finance.transaction",
            ),
        ),
    ]
