# Generated by Django 6.0.4 on 2026-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_transaction_account_transaction_is_transfer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financesettings",
            name="ai_create_categories",
            field=models.BooleanField(default=True),
        ),
    ]
