# Generated by Django 6.0.4 on 2026-06-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_financesettings_ai_create_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
