# Generated by Django 6.0.4 on 2026-06-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
