# Generated by Django 6.0.4 on 2026-06-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
