"""
Django settings for lexroom_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import datetime
from pathlib import Path

import environ
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env: environ.Env = environ.Env()

READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", default=False)
if READ_DOT_ENV_FILE:
    # OS environment variables take precedence over variables from .env
    env.read_env(str(BASE_DIR / ".env"))


# under_backend/
APPS_DIR = BASE_DIR / "under_backend" / "apps"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = True
# https://docs.djangoproject.com/en/5.2/ref/settings/#secret-key
SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="topXUUoKkXYwTRYuG0FR9Tlwica4K48c3Nlcmb4Pe0f1d4M4FcMnQzBIVHcQbNq9",
)

ALLOWED_HOSTS = []

# APPS

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "corsheaders",
    "ninja",  # added to include JavaScript bundled for OpenAPI/Swagger UI
    "ninja_extra",  # and we use ninja-schema for validation that wrap Django models

]

# MIDDLEWARE
# https://docs.djangoproject.com/en/5.2/settings/#middleware

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "servestatic.middleware.ServeStaticMiddleware",  # serve static files through Django always
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "lexroom_backend.apps.common.middlewares.LogRequestTimeMiddleware",  # appbackend decorator @log_execution_time
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# URLS
# https://docs.djangoproject.com/en/5.2/ref/settings/#root-urlconf
ROOT_URLCONF = "under_backend.urls"
# https://docs.djangoproject.com/en/5.2/ref/settings/#wsgi-application
# commented because we use daphne runserver for ASGI in "development" env
# WSGI_APPLICATION = "lexroom_backend.wsgi.application"  # noqa: ERA001

# AUTHENTICATION
# https://docs.djangoproject.com/en/5.2/ref/settings/#authentication-backends
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-user-model
AUTH_USER_MODEL = "common.LexroomUser"


# PASSWORDS
# https://docs.djangoproject.com/en/5.2/ref/settings/#password-hashers
PASSWORD_HASHERS = [
    # https://docs.djangoproject.com/en/5.2/topics/auth/passwords/#using-bcrypt-with-django
    # compatibility with old passwords from appbackend adding prefix "bcrypt$"
    "django.contrib.auth.hashers.BCryptPasswordHasher",
]
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/dev/ref/settings/#static-root
STATIC_ROOT = str(BASE_DIR / "staticfiles")
# https://docs.djangoproject.com/en/5.2/ref/settings/#static-url
STATIC_URL = "static/"

# Use the same storage backend as production to ensure manifest files are created
# This allows collectstatic to work at build time with base settings
STORAGES = {
    "staticfiles": {
        "BACKEND": "servestatic.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# SECURITY
# https://docs.djangoproject.com/en/5.2/ref/settings/#session-cookie-httponly
SESSION_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/5.2/ref/settings/#csrf-cookie-httponly
CSRF_COOKIE_HTTPONLY = True
# https://docs.djangoproject.com/en/5.2/ref/settings/#x-frame-options
X_FRAME_OPTIONS = "DENY"

# CORS
# ------------------------------------------------------------------------------
CORS_ALLOW_HEADERS = (
    *default_headers,
    *env.list("CORS_ALLOW_HEADERS", default=[]),
)
CORS_ALLOWED_ORIGIN_REGEXES = env.list("CORS_ALLOWED_ORIGIN_REGEXES", default=[])

# ADMIN
# ------------------------------------------------------------------------------
# Django Admin URL.
ADMIN_URL = "admin/"

# EMAIL
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#email-backend
EMAIL_BACKEND = env(
    "DJANGO_EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)
# https://docs.djangoproject.com/en/5.2/ref/settings/#email-timeout
EMAIL_TIMEOUT = 5

# LOGGING
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/5.2/ref/settings/#logging
# See https://docs.djangoproject.com/en/5.2/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {"level": "INFO", "handlers": ["console"]},
}

# NINJA_JWT
# ------------------------------------------------------------------------------
NINJA_JWT = {
    "AUTH_TOKEN_CLASSES": ("ninja_jwt.tokens.AccessToken",),
    "USER_ID_FIELD": "email",
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=30),
    "ALGORITHM": env("AUTH_ALGORITHM", default="HS256"),  # default
}

# NINJA_EXTRA
# ------------------------------------------------------------------------------
NINJA_EXTRA = {
    "INJECTOR_MODULES": [
        "under_backend.services.injection.ServicesModule"  # Uses real implementation
    ]
}
